name: 'Mend Slack Notifier'

on:
  discussion:
    types: [labeled]

permissions:
  discussions: read

jobs:
  slack:
    if: contains(github.event.label.name, 'mend-app')
    runs-on: ubuntu-latest
    steps:
      - name: Post to Slack
        id: slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          channel-id: 'C05NLTMGCJC'
          # For posting a simple plain text message
          slack-message: '<${{ github.event.discussion.html_url }}|${{ github.event.discussion.title }}>'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
